# Site settings
title: Jaric Sng Notes
description: Modern-Blog A Elegant template for Jekyll
keywords: Modern, Blogging, Fun
author: Jaric Sng
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site


plugins:
 - jekyll-feed
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-avatar
 - jemoji
 - jekyll-mentions

theme: jekyll-theme-cayman